/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary": "#eec200",
        "inverse-surface": "#dae2fd",
        "surface-tint": "#c0c1ff",
        "surface-variant": "#2d3449",
        "on-primary-container": "#0d0096",
        "primary-fixed": "#e1e0ff",
        "primary": "#c0c1ff",
        "on-secondary-container": "#00311f",
        "secondary-container": "#00a572",
        "on-surface-variant": "#c7c4d7",
        "inverse-primary": "#494bd6",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#c0c1ff",
        "on-error": "#690005",
        "on-primary": "#1000a9",
        "on-primary-fixed-variant": "#2f2ebe",
        "tertiary-fixed-dim": "#eec200",
        "secondary": "#4edea3",
        "on-tertiary-fixed-variant": "#574500",
        "surface-container-lowest": "#060e20",
        "secondary-fixed-dim": "#4edea3",
        "background": "#0b1326",
        "on-error-container": "#ffdad6",
        "tertiary-container": "#cea700",
        "outline-variant": "#464554",
        "on-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        "surface-container": "#171f33",
        "error-container": "#93000a",
        "on-primary-fixed": "#07006c",
        "outline": "#908fa0",
        "on-secondary-fixed": "#002113",
        "surface-container-highest": "#2d3449",
        "on-background": "#dae2fd",
        "on-tertiary-container": "#4e3e00",
        "surface-container-low": "#131b2e",
        "on-tertiary-fixed": "#231b00",
        "on-tertiary": "#3c2f00",
        "surface-dim": "#0b1326",
        "on-secondary": "#003824",
        "on-secondary-fixed-variant": "#005236",
        "surface-container-high": "#222a3d",
        "secondary-fixed": "#6ffbbe",
        "primary-container": "#8083ff",
        "surface-bright": "#31394d",
        "surface": "#0b1326",
        "tertiary-fixed": "#ffe083"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      spacing: {
        "margin-mobile": "16px",
        "margin-desktop": "40px",
        "base": "8px",
        "container-max": "1280px",
        "gutter": "24px",
        "bento-gap": "16px"
      },
      fontFamily: {
        "label-caps": ["JetBrains Mono", "monospace"],
        "body-md": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "display": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"]
      },
      fontSize: {
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.1em", "fontWeight": "700"}],
        "body-md": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["30px", {"lineHeight": "1.3", "fontWeight": "600"}],
        "display": ["64px", {"lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "headline-lg": ["48px", {"lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "700"}],
        "code-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "headline-lg-mobile": ["32px", {"lineHeight": "1.2", "fontWeight": "700"}],
        "body-lg": ["18px", {"lineHeight": "1.6", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
